# TwoMaze 게임 소스 파일
TWOMAZE_SRC := $(GAMES_DIR)/twomaze/twomaze_state.cpp

# TwoMaze 알고리즘 파일
TWOMAZE_ALGO := $(ALGO_DIR_2P)/alternate/random.cpp \
                $(ALGO_DIR_2P)/alternate/minimax.cpp \
                $(ALGO_DIR_2P)/alternate/alphabeta.cpp \
                $(ALGO_DIR_2P)/alternate/deepening.cpp \
                $(ALGO_DIR_2P)/alternate/mc.cpp \
                $(ALGO_DIR_2P)/alternate/mcts.cpp \
                $(ALGO_DIR_2P)/alternate/thunder.cpp