# AutoMaze 게임 소스 파일
AUTOMAZE_SRC := $(GAMES_DIR)/automaze/automaze_state.cpp
AUTOMAZE_ALGO := $(ALGO_DIR)/without_context/hillclimb.cpp \
                 $(ALGO_DIR)/without_context/simulated_annealing.cpp